---
- name  : "Lynis Report Generation"
  hosts : pilot,monitoring,logging
  become: yes
  tasks :
    - name: "Stop Firewall Service"
      shell: systemctl stop ufw

    - name: "Disable Firewall Service"
      shell: systemctl disable ufw

    - name: "Mask Firewall Service"
      shell: systemctl mask ufw

    # - name: "Download the Lynis Repo"
    #   shell: git clone https://github.com/CISOfy/lynis /opt/pinakastra/lynis

    - name: "Change the working directory to /opt/pinakastra/lynis"
      shell: ./lynis audit system | ansi2html -l > `hostname`_after_hardening.html
      args:
        chdir: /opt/pinakastra/lynis
