---

- name  : "Prometheus Setup"
  hosts : monitoring
  become: yes
  tasks :
    - name: "Download the Monitoring Repo"
      shell: git clone https://github.com/swadhin4431/infra_mon_install.git /opt/monitoring

    - name: "Change the working directory to /opt/pinakastra/monitoring"
      shell: /bin/bash prometheus.sh
      args:
        chdir: /opt/monitoring

    - name: "Remove the Monitoring Repo"
      shell: rm -rf /opt/monitoring
