#Script Name: Prometheus Rules Setup                                                                                        
#Description: Promethues Rules Setup YAML                                                                       
#Args:                                                                                    
#Author: Yashwant Bokadia (Pinakastra Computing)                                              
#Email: cloud@pinakastra.com                                       

groups:
  - name: example_alert
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 5m
        labels:
          severity: page
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."
